name: MC-CAPTCHA
version: 1.0-ALPHA-SNAPSHOT
main: net.wuffs.mccaptcha.Override.Main
api-version: 1.16
authors: [ SparksTheFolf ]
description: MC-CAPTCHA authentication for Public and Private Servers
website: wuffs.net
